### ISSUE TITLE
Change response structure to reflect apiary

### ISSUE THREAD

**Issue by atulb98** [EZPlanner/ezplanner-planner-service#2]

**Comment by zahin-mohammad** [comment]
Fixed in
https://github.com/EZPlanner/ezplanner-planner-service/commit/1f8ed55e09c67aee10792604e9860d11ea4090b5
https://github.com/EZPlanner/ezplanner-planner-service/commit/d9735a6b32d313dc5b61dbc6a90c6ea0ddeec0ec
